[theme]

# Primary 
primaryColor = '#E694FF'

# Background color 
backgroundColor = '#20002b'

# Secondary Background color 
secondaryBackgroundColor= '#3d1e47'

# Color for text
textColor = '#FFFFFF'

# Font family 
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
